Algoritmo "contador"

Var
//VARIÁVEIS
valormaximo,contador: inteiro


Inicio
// PEÇO AO USUÁRIO UM NÚMERO P/ CONTAR ATÉ ELE
escreval("DIGITE UM NÚMERO: ")
leia(valormaximo)
//CONTADOR RECEBE VALOR
contador <- 0

//EXIBE AO USUÁRIO OS NÚMEROS
escreval("CONTAGEM: ")

//LAÇO DE REPETIÇÃO
enquanto (contador <= valormaximo) faca
escreval(contador, " ")
contador <- contador + 1
fimenquanto
//mensagem do término do fim do laço
escreval("ACABOU")

Fimalgoritmo