Algoritmo "semnome"
// Exercício 2 — Sistema de Desconto da Papelaria
//Contexto
//Uma papelaria deseja informatizar o sistema de vendas durante a volta às aulas. Dependendo do valor total das compras, o cliente poderá receber descontos especiais.
//O sistema deverá solicitar:
//Nome do cliente
//Valor da compra
//Regras:
//Compras acima de R$ 500 recebem 15% de desconto.
//Compras entre R$ 200 e R$ 500 recebem 10%.
//Compras abaixo de R$ 200 recebem 5%.
//Além disso:
//Mostrar o valor do desconto.
//Mostrar o valor final da compra.
//O que o programa deve fazer
//Calcular desconto conforme faixa de valor
//Mostrar valor final
//Utilizar estruturas condicionais encadeadas

Var



Inicio



Fimalgoritmo