Algoritmo "PORTALALUNOLISTA1ATIV8"
//8. Portal do Aluno Tech Contexto
 Uma escola técnica deseja criar um portal acadêmico.
O estudante poderá:
• Consultar notas
• Consultar faltas
• Enviar dúvidas ao professor
• Encerrar sessão
Conceitos
• Menus
• Entrada de texto
• Condicionais
Var
// Seção de Declarações das variáveis
consultanotas,notas: inteiro
faltas: inteiro
duvidas: caractere
encerrar: caractere
entrada: caractere
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

escreval("===PORTAL===")
escreval ("1-ADICIONAR NOTAS")
escreval("2-CONSULTAR FALTAS")
escreval("3-CONSULTAR NOTAS")
escreval("3-DÚVIDAS")
Fimalgoritmo