Algoritmo "TABUADALISTA1ATIV5"
//5. Treinador de Matemática para Programadores
//Contexto
//Uma startup desenvolveu um aplicativo para ajudar futuros programadores a melhorar cálculo mental.
//O usuário escolhe um número entre 1 e 10 e o sistema apresenta sua tabuada completa.
//Conceitos
//• Laço PARA
//• Validação de entrada
Var
// DECLARO AS VARIÁVEIS
num,contador,resultado: inteiro
Inicio
//PEÇO AO USUÁRIO P/ DECLARAR UM NÚMERO
escreva("DIGITE UM NÚMERO: ")
leia(num)
   
para contador de 0 ate 10 faca
resultado <- num * contador
escreval("***TABUADA DO ",num," ***")
escreval(num," X ",contador," = ",resultado)
fimpara
Fimalgoritmo